cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np1 --sampling 1 --epoch 1 --overwrite 
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np5 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer Np7 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcN --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm1c1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNm3 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5c1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZjet0 --layer NcNp5 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np1 --sampling 1 --epoch 1 --overwrite 
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np5 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer Np7 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcN --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm1c1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNm3 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5c1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphijet0 --layer NcNp5 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np1 --sampling 1 --epoch 1 --overwrite 
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.3 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.3 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.3 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.3 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.3 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.5 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.5 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.5 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.5 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.5 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.6 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.6 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.6 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.6 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.6 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.8 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.8 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.8 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.8 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 0.8 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 1 --epoch 0.3
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 1 --epoch 0.5
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 1 --epoch 0.6
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 1 --epoch 0.8
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np5 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer Np7 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcN --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm1c1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNm3 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5c1 --sampling 1 --epoch 1
cmssw python train_TWZ_3l.py --mva mlp --variables randZWdphidRnonZ --layer NcNp5 --sampling 1 --epoch 1
