python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO  #SPLIT40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M50 #SPLIT30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 #SPLIT250
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 #SPLIT80
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTHad_pow_CP5 #SPLIT40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTHTobb #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTHnobb #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTWToLNu #SPLIT50
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTWToQQ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTZToQQ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTZToLLNuNu #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTZToLLNuNu_m1to10 #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample T_tch_pow #SPLIT80
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TBar_tch_pow #SPLIT80
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample T_tWch #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TBar_tWch #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample tZq_ll #SPLIT17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample tWll_thad_Wlept_DR #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample tWll_thad_Wlept_DS #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample tWll_tlept_Whad_DR #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample tWll_tlept_Whad_DS #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample tWll_tlept_Wlept_DR #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample tWll_tlept_Wlept_DS #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample WW #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample WZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample WWW_4F #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample WWZ_4F #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample WZZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample ZZZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTTT #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTWW #SPLIT3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTWZ
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v1 --sample TTZZ
